export const marksOfCars = [
    {value: 'acura', label: 'Acura'},
    {value: 'alfa romeo', label: 'Alfa Romeo'},
    {value: 'amc', label: 'AMC'},
    {value: 'aston martin', label: 'Aston Martin'},
    {value: 'audi', label: 'Audi'},
    {value: 'avanti', label: 'Avanti'},
    {value: 'bentley', label: 'Bentley'},
    {value: 'bmw', label: 'BMW'},
    {value: 'buick', label: 'Buick'},
    {value: 'cadillac', label: 'Cadillac'},
    {value: 'chevrolet', label: 'Chevrolet'},
    {value: 'chrysler', label: 'Chrysler'},
  ];

export const modelsOfCars = [
    {value: '2.2CL', label: '2.2CL', link: 'acura'},
    {value: '2.3CL', label: '2.3CL', link: 'acura'},
    {value: '3.0CL', label: '3.0CL', link: 'acura'},
    {value: '3.2CL', label: '3.2CL', link: 'acura'},
    {value: 'ILX', label: 'ILX', link: 'acura'},
    {value: 'Integra', label: 'Integra', link: 'acura'},
    {value: 'Legend', label: 'Legend', link: 'acura'},
    {value: 'MDX', label: 'MDX', link: 'acura'},
    {value: 'NSX', label: 'NSX', link: 'acura'},
    {value: 'RDX', label: 'RDX', link: 'acura'},
    {value: '3.5 RL', label: '3.5 RL', link: 'acura'},
    {value: 'RL', label: 'RL', link: 'acura'},
    {value: 'RSX', label: 'RSX', link: 'acura'},
    {value: 'SLX', label: 'SLX', link: 'acura'},
    {value: '2.5TL', label: '2.5TL', link: 'acura'},
    {value: '3.2TL', label: '3.2TL', link: 'acura'},
    {value: 'TL', label: 'TL', link: 'acura'},
    {value: 'TSX', label: 'TSX', link: 'acura'},
    {value: 'Vigor', label: 'Vigor', link: 'acura'},
    {value: 'ZDX', label: 'ZDX', link: 'acura'},
    {value: '164', label: '164', link: 'alfa romeo'},
    {value: '8C Competizione', label: '8C Competizione', link: 'alfa romeo'},
    {value: 'GTV-6', label: 'GTV-6', link: 'alfa romeo'},
    {value: 'Milano', label: 'Milano', link: 'alfa romeo'},
    {value: 'Spider', label: 'Spider', link: 'alfa romeo'},
    {value: 'Alliance', label: 'Alliance', link: 'amc'},
    {value: 'Concord', label: 'Concord', link: 'amc'},
    {value: 'Eagle', label: 'Eagle', link: 'amc'},
    {value: 'Encore', label: 'Encore', link: 'amc'},
    {value: 'Spirit', label: 'Spirit', link: 'amc'},
    {value: 'DB7', label: 'DB7', link: 'aston martin'},
    {value: 'DB9', label: 'DB9', link: 'aston martin'},
    {value: 'DBS', label: 'DBS', link: 'aston martin'},
    {value: 'Lagonda', label: 'Lagonda', link: 'aston martin'},
    {value: 'Rapide', label: 'Rapide', link: 'aston martin'},
    {value: 'V12 Vantage', label: 'V12 Vantage', link: 'aston martin'},
    {value: 'V8 Vantage', label: 'V8 Vantage', link: 'aston martin'},
    {value: 'Vanquish', label: 'Vanquish', link: 'aston martin'},
    {value: 'Virage', label: 'Virage', link: 'aston martin'},
    {value: '100', label: '100', link: 'audi'},
    {value: '200', label: '200', link: 'audi'},
    {value: '4000', label: '4000', link: 'audi'},
    {value: '5000', label: '5000', link: 'audi'},
    {value: '80', label: '80', link: 'audi'},
    {value: '90', label: '90', link: 'audi'},
    {value: 'A3', label: 'A3', link: 'audi'},
    {value: 'A4', label: 'A4', link: 'audi'},
    {value: 'A5', label: 'A5', link: 'audi'},
    {value: 'A6', label: 'A6', link: 'audi'},
    {value: 'A7', label: 'A7', link: 'audi'},
    {value: 'A8', label: 'A8', link: 'audi'},
    {value: 'allroad', label: 'allroad', link: 'audi'},
    {value: 'Cabriolet', label: 'Cabriolet', link: 'audi'},
    {value: 'Coupe', label: 'Coupe', link: 'audi'},
    {value: 'Q3', label: 'Q3', link: 'audi'},
    {value: 'Q5', label: 'Q5', link: 'audi'},
    {value: 'Q7', label: 'Q7', link: 'audi'},
    {value: 'Quattro', label: 'Quattro', link: 'audi'},
    {value: 'RS 4', label: 'RS 4', link: 'audi'},
    {value: 'RS 5', label: 'RS 5', link: 'audi'},
    {value: 'RS 6', label: 'RS 6', link: 'audi'},
    {value: 'S4', label: 'S4', link: 'audi'},
    {value: 'S5', label: 'S5', link: 'audi'},
    {value: 'S6', label: 'S6', link: 'audi'},
    {value: 'S7', label: 'S7', link: 'audi'},
    {value: 'S8', label: 'S8', link: 'audi'},
    {value: 'TT', label: 'TT', link: 'audi'},
    {value: 'TT RS', label: 'TT RS', link: 'audi'},
    {value: 'TTS', label: 'TTS', link: 'audi'},
    {value: 'V8 Quattro', label: 'V8 Quattro', link: 'audi'},
    {value: 'Convertible', label: 'Convertible', link: 'avanti'},
    {value: 'Coupe', label: 'Coupe', link: 'avanti'},
    {value: 'Sedan', label: 'Sedan', link: 'avanti'},
    {value: 'Arnage', label: 'Arnage', link: 'bentley'},
    {value: 'Azure', label: 'Azure', link: 'bentley'},
    {value: 'Brooklands', label: 'Brooklands', link: 'bentley'},
    {value: 'Brooklands', label: 'Brooklands', link: 'bentley'},
    {value: 'Continental', label: 'Continental', link: 'bentley'},
    {value: 'Corniche', label: 'Corniche', link: 'bentley'},
    {value: 'Eight', label: 'Eight', link: 'bentley'},
    {value: 'Mulsanne', label: 'Mulsanne', link: 'bentley'},
    {value: 'Turbo R', label: 'Turbo R', link: 'bentley'},
    {value: '128i', label: '128i', link: 'bmw'},
    {value: '135i', label: '135i', link: 'bmw'},
    {value: '135is', label: '135is', link: 'bmw'},
    {value: '318i', label: '318i', link: 'bmw'},
    {value: '318iC', label: '318iC', link: 'bmw'},
    {value: '318iS', label: '318iS', link: 'bmw'},
    {value: '318ti', label: '318ti', link: 'bmw'},
    {value: '320i', label: '320i', link: 'bmw'},
    {value: '323ci', label: '323ci', link: 'bmw'},
    {value: '323i', label: '323i', link: 'bmw'},
    {value: '323is', label: '323is', link: 'bmw'},
    {value: '323iT', label: '323iT', link: 'bmw'},
    {value: '325Ci', label: '325Ci', link: 'bmw'},
    {value: '325e', label: '325e', link: 'bmw'},
    {value: '325es', label: '325es', link: 'bmw'},
    {value: '325i', label: '325i', link: 'bmw'},
    {value: '325is', label: '325is', link: 'bmw'},
    {value: '325iX', label: '325iX', link: 'bmw'},
    {value: '325xi', label: '325xi', link: 'bmw'},
    {value: '328Ci', label: '328Ci', link: 'bmw'},
    {value: '328i', label: '328i', link: 'bmw'},
    {value: '328iS', label: '328iS', link: 'bmw'},
    {value: '328xi', label: '328xi', link: 'bmw'},
    {value: '330Ci', label: '330Ci', link: 'bmw'},
    {value: '330i', label: '330i', link: 'bmw'},
    {value: '330xi', label: '330xi', link: 'bmw'},
    {value: '335d', label: '335d', link: 'bmw'},
    {value: '335i', label: '335i', link: 'bmw'},
    {value: '335is', label: '335is', link: 'bmw'},
    {value: '335xi', label: '335xi', link: 'bmw'},
    {value: 'ActiveHybrid 3', label: 'ActiveHybrid 3', link: 'bmw'},
    {value: '325', label: '325', link: 'bmw'},
    {value: '524td', label: '524td', link: 'bmw'},
    {value: '525i', label: '525i', link: 'bmw'},
    {value: '525xi', label: '525xi', link: 'bmw'},
    {value: '528e', label: '528e', link: 'bmw'},
    {value: '528i', label: '528i', link: 'bmw'},
    {value: '528iT', label: '528iT', link: 'bmw'},
    {value: '528xi', label: '528xi', link: 'bmw'},
    {value: '530i', label: '530i', link: 'bmw'},
    {value: '530iT', label: '530iT', link: 'bmw'},
    {value: '530xi', label: '530xi', link: 'bmw'},
    {value: '533i', label: '533i', link: 'bmw'},
    {value: '535i', label: '535i', link: 'bmw'},
    {value: '535i Gran Turismo', label: '535i Gran Turismo', link: 'bmw'},
    {value: '535xi', label: '535xi', link: 'bmw'},
    {value: '540i', label: '540i', link: 'bmw'},
    {value: '545i', label: '545i', link: 'bmw'},
    {value: '550i', label: '550i', link: 'bmw'},
    {value: '550i Gran Turismo', label: '550i Gran Turismo', link: 'bmw'},
    {value: 'ActiveHybrid 5', label: 'ActiveHybrid 5', link: 'bmw'},
    {value: '633CSi', label: '633CSi', link: 'bmw'},
    {value: '635CSi', label: '635CSi', link: 'bmw'},
    {value: '640i', label: '640i', link: 'bmw'},
    {value: '640i Gran Coupe', label: '640i Gran Coupe', link: 'bmw'},
    {value: '645Ci', label: '645Ci', link: 'bmw'},
    {value: '650i', label: '650i', link: 'bmw'},
    {value: '650i Gran Coupe', label: '650i Gran Coupe', link: 'bmw'},
    {value: 'L6', label: 'L6', link: 'bmw'},
    {value: '733i', label: '733i', link: 'bmw'},
    {value: '735i', label: '735i', link: 'bmw'},
    {value: '735iL', label: '735iL', link: 'bmw'},
    {value: '740i', label: '740i', link: 'bmw'},
    {value: '740iL', label: '740iL', link: 'bmw'},
    {value: '740Li', label: '740Li', link: 'bmw'},
    {value: '745i', label: '745i', link: 'bmw'},
    {value: '745Li', label: '745Li', link: 'bmw'},
    {value: '750i', label: '750i', link: 'bmw'},
    {value: '750iL', label: '750iL', link: 'bmw'},
    {value: '750Li', label: '750Li', link: 'bmw'},
    {value: '760i', label: '760i', link: 'bmw'},
    {value: '760Li', label: '760Li', link: 'bmw'},
    {value: 'ActiveHybrid 7', label: 'ActiveHybrid 7', link: 'bmw'},
    {value: 'Alpina B7', label: 'Alpina B7', link: 'bmw'},
    {value: '840Ci', label: '840Ci', link: 'bmw'},
    {value: '850Ci', label: '850Ci', link: 'bmw'},
    {value: '850CSi', label: '850CSi', link: 'bmw'},
    {value: '850i', label: '850i', link: 'bmw'},
    {value: 'L7', label: 'L7', link: 'bmw'},
    {value: '1 Series M', label: '1 Series M', link: 'bmw'},
    {value: 'M Coupe', label: 'M Coupe', link: 'bmw'},
    {value: 'M Roadster', label: 'M Roadster', link: 'bmw'},
    {value: 'M3', label: 'M3', link: 'bmw'},
    {value: 'M5', label: 'M5', link: 'bmw'},
    {value: 'M6', label: 'M6', link: 'bmw'},
    {value: 'X5 M', label: 'X5 M', link: 'bmw'},
    {value: 'X6 M', label: 'X6 M', link: 'bmw'},
    {value: 'ActiveHybrid X6', label: 'ActiveHybrid X6', link: 'bmw'},
    {value: 'X1', label: 'X1', link: 'bmw'},
    {value: 'X3', label: 'X3', link: 'bmw'},
    {value: 'X5', label: 'X5', link: 'bmw'},
    {value: 'X6', label: 'X6', link: 'bmw'},
    {value: 'Z3', label: 'Z3', link: 'bmw'},
    {value: 'Z4', label: 'Z4', link: 'bmw'},
    {value: 'Z8', label: 'Z8', link: 'bmw'},
    {value: 'Century', label: 'Century', link: 'buick'},
    {value: 'Electra', label: 'Electra', link: 'buick'},
    {value: 'Enclave', label: 'Enclave', link: 'buick'},
    {value: 'Encore', label: 'Encore', link: 'buick'},
    {value: 'LaCrosse', label: 'LaCrosse', link: 'buick'},
    {value: 'Le Sabre', label: 'Le Sabre', link: 'buick'},
    {value: 'Lucerne', label: 'Lucerne', link: 'buick'},
    {value: 'Park Avenue', label: 'Park Avenue', link: 'buick'},
    {value: 'Rainier', label: 'Rainier', link: 'buick'},
    {value: 'Reatta', label: 'Reatta', link: 'buick'},
    {value: 'Regal', label: 'Regal', link: 'buick'},
    {value: 'Rendezvous', label: 'Rendezvous', link: 'buick'},
    {value: 'Riviera', label: 'Riviera', link: 'buick'},
    {value: 'Roadmaster', label: 'Roadmaster', link: 'buick'},
    {value: 'Skyhawk', label: 'Skyhawk', link: 'buick'},
    {value: 'Skylark', label: 'Skylark', link: 'buick'},
    {value: 'Somerset', label: 'Somerset', link: 'buick'},
    {value: 'Terraza', label: 'Terraza', link: 'buick'},
    {value: 'Verano', label: 'Verano', link: 'buick'},
    {value: 'Allante', label: 'Allante', link: 'cadillac'},
    {value: 'ATS', label: 'ATS', link: 'cadillac'},
    {value: 'Brougham', label: 'Brougham', link: 'cadillac'},
    {value: 'Catera', label: 'Catera', link: 'cadillac'},
    {value: 'Cimarron', label: 'Cimarron', link: 'cadillac'},
    {value: 'CTS', label: 'CTS', link: 'cadillac'},
    {value: 'De Ville', label: 'De Ville', link: 'cadillac'},
    {value: 'DTS', label: 'DTS', link: 'cadillac'},
    {value: 'Eldorado', label: 'Eldorado', link: 'cadillac'},
    {value: 'Escalade', label: 'Escalade', link: 'cadillac'},
    {value: 'Escalade ESV', label: 'Escalade ESV', link: 'cadillac'},
    {value: 'Escalade EXT', label: 'Escalade EXT', link: 'cadillac'},
    {value: 'Fleetwood', label: 'Fleetwood', link: 'cadillac'},
    {value: 'Seville', label: 'Seville', link: 'cadillac'},
    {value: 'SRX', label: 'SRX', link: 'cadillac'},
    {value: 'STS', label: 'STS', link: 'cadillac'},
    {value: 'XLR', label: 'XLR', link: 'cadillac'},
    {value: 'XTS', label: 'XTS', link: 'cadillac'},
    {value: 'Astro', label: 'Astro', link: 'chevrolet'},
    {value: 'Avalanche', label: 'Avalanche', link: 'chevrolet'},
    {value: 'Aveo', label: 'Aveo', link: 'chevrolet'},
    {value: 'Aveo5', label: 'Aveo5', link: 'chevrolet'},
    {value: 'Beretta', label: 'Beretta', link: 'chevrolet'},
    {value: 'Blazer', label: 'Blazer', link: 'chevrolet'},
    {value: 'Camaro', label: 'Camaro', link: 'chevrolet'},
    {value: 'Caprice', label: 'Caprice', link: 'chevrolet'},
    {value: 'Captiva Sport', label: 'Captiva Sport', link: 'chevrolet'},
    {value: 'Cavalier', label: 'Cavalier', link: 'chevrolet'},
    {value: 'Celebrity', label: 'Celebrity', link: 'chevrolet'},
    {value: 'Chevette', label: 'Chevette', link: 'chevrolet'},
    {value: 'Citation', label: 'Citation', link: 'chevrolet'},
    {value: 'Cobalt', label: 'Cobalt', link: 'chevrolet'},
    {value: 'Colorado', label: 'Colorado', link: 'chevrolet'},
    {value: 'Corsica', label: 'Corsica', link: 'chevrolet'},
    {value: 'Corvette', label: 'Corvette', link: 'chevrolet'},
    {value: 'Cruze', label: 'Cruze', link: 'chevrolet'},
    {value: 'El Camino', label: 'El Camino', link: 'chevrolet'},
    {value: 'Equinox', label: 'Equinox', link: 'chevrolet'},
    {value: 'Express Van', label: 'Express Van', link: 'chevrolet'},
    {value: 'G Van', label: 'G Van', link: 'chevrolet'},
    {value: 'HHR', label: 'HHR', link: 'chevrolet'},
    {value: 'Impala', label: 'Impala', link: 'chevrolet'},
    {value: 'Kodiak C4500', label: 'Kodiak C4500', link: 'chevrolet'},
    {value: 'Lumina', label: 'Lumina', link: 'chevrolet'},
    {value: 'Lumina APV', label: 'Lumina APV', link: 'chevrolet'},
    {value: 'LUV', label: 'LUV', link: 'chevrolet'},
    {value: 'Malibu', label: 'Malibu', link: 'chevrolet'},
    {value: 'Metro', label: 'Metro', link: 'chevrolet'},
    {value: 'Monte Carlo', label: 'Monte Carlo', link: 'chevrolet'},
    {value: 'Nova', label: 'Nova', link: 'chevrolet'},
    {value: 'Prizm', label: 'Prizm', link: 'chevrolet'},
    {value: 'S10 Blazer', label: 'S10 Blazer', link: 'chevrolet'},
    {value: 'S10 Pickup', label: 'S10 Pickup', link: 'chevrolet'},
    {value: 'Silverado and other C/K1500', label: 'Silverado and other C/K1500', link: 'chevrolet'},
    {value: 'Silverado and other C/K2500', label: 'Silverado and other C/K2500', link: 'chevrolet'},
    {value: 'Silverado and other C/K3500', label: 'Silverado and other C/K3500', link: 'chevrolet'},
    {value: 'Sonic', label: 'Sonic', link: 'chevrolet'},
    {value: 'Spark', label: 'Spark', link: 'chevrolet'},
    {value: 'Spectrum', label: 'Spectrum', link: 'chevrolet'},
    {value: 'Sprint', label: 'Sprint', link: 'chevrolet'},
    {value: 'SSR', label: 'SSR', link: 'chevrolet'},
    {value: 'Suburban', label: 'Suburban', link: 'chevrolet'},
    {value: 'Tahoe', label: 'Tahoe', link: 'chevrolet'},
    {value: 'Tracker', label: 'Tracker', link: 'chevrolet'},
    {value: 'TrailBlazer', label: 'TrailBlazer', link: 'chevrolet'},
    {value: 'TrailBlazer EXT', label: 'TrailBlazer EXT', link: 'chevrolet'},
    {value: 'Traverse', label: 'Traverse', link: 'chevrolet'},
    {value: 'Uplander', label: 'Uplander', link: 'chevrolet'},
    {value: 'Venture', label: 'Venture', link: 'chevrolet'},
    {value: 'Volt', label: 'Volt', link: 'chevrolet'},
    {value: '200', label: '200', link: 'chrysler'},
    {value: '300', label: '300', link: 'chrysler'},
    {value: '300M', label: '300M', link: 'chrysler'},
    {value: 'Aspen', label: 'Aspen', link: 'chrysler'},
    {value: 'Caravan', label: 'Caravan', link: 'chrysler'},
    {value: 'Cirrus', label: 'Cirrus', link: 'chrysler'},
    {value: 'Concorde', label: 'Concorde', link: 'chrysler'},
    {value: 'Conquest', label: 'Conquest', link: 'chrysler'},
    {value: 'Cordoba', label: 'Cordoba', link: 'chrysler'},
    {value: 'Crossfire', label: 'Crossfire', link: 'chrysler'},
    {value: 'E Class', label: 'E Class', link: 'chrysler'},
    {value: 'Fifth Avenue', label: 'Fifth Avenue', link: 'chrysler'},
    {value: 'Grand Voyager', label: 'Grand Voyager', link: 'chrysler'},
    {value: 'Imperial', label: 'Imperial', link: 'chrysler'},
    {value: 'Intrepid', label: 'Intrepid', link: 'chrysler'},
    {value: 'Laser', label: 'Laser', link: 'chrysler'},
    {value: 'LeBaron', label: 'LeBaron', link: 'chrysler'},
    {value: 'LHS', label: 'LHS', link: 'chrysler'},
    {value: 'Neon', label: 'Neon', link: 'chrysler'},
    {value: 'New Yorker', label: 'New Yorker', link: 'chrysler'},
    {value: 'Newport', label: 'Newport', link: 'chrysler'},
    {value: 'Pacifica', label: 'Pacifica', link: 'chrysler'},
    {value: 'Prowler', label: 'Prowler', link: 'chrysler'},
    {value: 'PT Cruiser', label: 'PT Cruiser', link: 'chrysler'},
    {value: 'Sebring', label: 'Sebring', link: 'chrysler'},
    {value: 'TC by Maserati', label: 'TC by Maserati', link: 'chrysler'},
    {value: 'Town &amp; Country', label: 'Town &amp; Country', link: 'chrysler'},
    {value: 'Voyager', label: 'Voyager', link: 'chrysler'},
      
];
