export const marksOfCars = [
    {value: 'acura', label: 'Acura'},
    {value: 'alfa romeo', label: 'Alfa Romeo'},
    {value: 'amc', label: 'AMC'},
    {value: 'aston martin', label: 'Aston Martin'},
    {value: 'audi', label: 'Audi'},
    {value: 'avanti', label: 'Avanti'},
    {value: 'bentley', label: 'Bentley'},
    {value: 'bmw', label: 'BMW'},
  ];

export const modelsOfCars = [
    {value: '2.2CL', label: '2.2CL', link: 'acura'},
    {value: '2.3CL', label: '2.3CL', link: 'acura'},
    {value: '3.0CL', label: '3.0CL', link: 'acura'},
    {value: '3.2CL', label: '3.2CL', link: 'acura'},
    {value: 'ILX', label: 'ILX', link: 'acura'},
    {value: 'Integra', label: 'Integra', link: 'acura'},
    {value: 'Legend', label: 'Legend', link: 'acura'},
    {value: 'MDX', label: 'MDX', link: 'acura'},
    {value: 'NSX', label: 'NSX', link: 'acura'},
    {value: 'RDX', label: 'RDX', link: 'acura'},
    {value: '3.5 RL', label: '3.5 RL', link: 'acura'},
    {value: 'RL', label: 'RL', link: 'acura'},
    {value: 'RSX', label: 'RSX', link: 'acura'},
    {value: 'SLX', label: 'SLX', link: 'acura'},
    {value: '2.5TL', label: '2.5TL', link: 'acura'},
    {value: '3.2TL', label: '3.2TL', link: 'acura'},
    {value: 'TL', label: 'TL', link: 'acura'},
    {value: 'TSX', label: 'TSX', link: 'acura'},
    {value: 'Vigor', label: 'Vigor', link: 'acura'},
    {value: 'ZDX', label: 'ZDX', link: 'acura'},
    {value: '164', label: '164', link: 'alfa romeo'},
    {value: '8C Competizione', label: '8C Competizione', link: 'alfa romeo'},
    {value: 'GTV-6', label: 'GTV-6', link: 'alfa romeo'},
    {value: 'Milano', label: 'Milano', link: 'alfa romeo'},
    {value: 'Spider', label: 'Spider', link: 'alfa romeo'},
    {value: 'Alliance', label: 'Alliance', link: 'amc'},
    {value: 'Concord', label: 'Concord', link: 'amc'},
    {value: 'Eagle', label: 'Eagle', link: 'amc'},
    {value: 'Encore', label: 'Encore', link: 'amc'},
    {value: 'Spirit', label: 'Spirit', link: 'amc'},
    {value: 'DB7', label: 'DB7', link: 'aston martin'},
    {value: 'DB9', label: 'DB9', link: 'aston martin'},
    {value: 'DBS', label: 'DBS', link: 'aston martin'},
    {value: 'Lagonda', label: 'Lagonda', link: 'aston martin'},
    {value: 'Rapide', label: 'Rapide', link: 'aston martin'},
    {value: 'V12 Vantage', label: 'V12 Vantage', link: 'aston martin'},
    {value: 'V8 Vantage', label: 'V8 Vantage', link: 'aston martin'},
    {value: 'Vanquish', label: 'Vanquish', link: 'aston martin'},
    {value: 'Virage', label: 'Virage', link: 'aston martin'},
    {value: '100', label: '100', link: 'audi'},
    {value: '200', label: '200', link: 'audi'},
    {value: '4000', label: '4000', link: 'audi'},
    {value: '5000', label: '5000', link: 'audi'},
    {value: '80', label: '80', link: 'audi'},
    {value: '90', label: '90', link: 'audi'},
    {value: 'A3', label: 'A3', link: 'audi'},
    {value: 'A4', label: 'A4', link: 'audi'},
    {value: 'A5', label: 'A5', link: 'audi'},
    {value: 'A6', label: 'A6', link: 'audi'},
    {value: 'A7', label: 'A7', link: 'audi'},
    {value: 'A8', label: 'A8', link: 'audi'},
    {value: 'allroad', label: 'allroad', link: 'audi'},
    {value: 'Cabriolet', label: 'Cabriolet', link: 'audi'},
    {value: 'Coupe', label: 'Coupe', link: 'audi'},
    {value: 'Q3', label: 'Q3', link: 'audi'},
    {value: 'Q5', label: 'Q5', link: 'audi'},
    {value: 'Q7', label: 'Q7', link: 'audi'},
    {value: 'Quattro', label: 'Quattro', link: 'audi'},
    {value: 'RS 4', label: 'RS 4', link: 'audi'},
    {value: 'RS 5', label: 'RS 5', link: 'audi'},
    {value: 'RS 6', label: 'RS 6', link: 'audi'},
    {value: 'S4', label: 'S4', link: 'audi'},
    {value: 'S5', label: 'S5', link: 'audi'},
    {value: 'S6', label: 'S6', link: 'audi'},
    {value: 'S7', label: 'S7', link: 'audi'},
    {value: 'S8', label: 'S8', link: 'audi'},
    {value: 'TT', label: 'TT', link: 'audi'},
    {value: 'TT RS', label: 'TT RS', link: 'audi'},
    {value: 'TTS', label: 'TTS', link: 'audi'},
    {value: 'V8 Quattro', label: 'V8 Quattro', link: 'audi'},
    {value: 'Convertible', label: 'Convertible', link: 'avanti'},
    {value: 'Coupe', label: 'Coupe', link: 'avanti'},
    {value: 'Sedan', label: 'Sedan', link: 'avanti'},
    {value: 'Arnage', label: 'Arnage', link: 'bentley'},
    {value: 'Azure', label: 'Azure', link: 'bentley'},
    {value: 'Brooklands', label: 'Brooklands', link: 'bentley'},
    {value: 'Brooklands', label: 'Brooklands', link: 'bentley'},
    {value: 'Continental', label: 'Continental', link: 'bentley'},
    {value: 'Corniche', label: 'Corniche', link: 'bentley'},
    {value: 'Eight', label: 'Eight', link: 'bentley'},
    {value: 'Mulsanne', label: 'Mulsanne', link: 'bentley'},
    {value: 'Turbo R', label: 'Turbo R', link: 'bentley'},
    {value: '128i', label: '128i', link: 'bmw'},
    {value: '135i', label: '135i', link: 'bmw'},
    {value: '135is', label: '135is', link: 'bmw'},
    {value: '318i', label: '318i', link: 'bmw'},
    {value: '318iC', label: '318iC', link: 'bmw'},
    {value: '318iS', label: '318iS', link: 'bmw'},
    {value: '318ti', label: '318ti', link: 'bmw'},
    {value: '320i', label: '320i', link: 'bmw'},
    {value: '323ci', label: '323ci', link: 'bmw'},
    {value: '323i', label: '323i', link: 'bmw'},
    {value: '323is', label: '323is', link: 'bmw'},
    {value: '323iT', label: '323iT', link: 'bmw'},
    {value: '325Ci', label: '325Ci', link: 'bmw'},
    {value: '325e', label: '325e', link: 'bmw'},
    {value: '325es', label: '325es', link: 'bmw'},
    {value: '325i', label: '325i', link: 'bmw'},
    {value: '325is', label: '325is', link: 'bmw'},
    {value: '325iX', label: '325iX', link: 'bmw'},
    {value: '325xi', label: '325xi', link: 'bmw'},
    {value: '328Ci', label: '328Ci', link: 'bmw'},
    {value: '328i', label: '328i', link: 'bmw'},
    {value: '328iS', label: '328iS', link: 'bmw'},
    {value: '328xi', label: '328xi', link: 'bmw'},
    {value: '330Ci', label: '330Ci', link: 'bmw'},
    {value: '330i', label: '330i', link: 'bmw'},
    {value: '330xi', label: '330xi', link: 'bmw'},
    {value: '335d', label: '335d', link: 'bmw'},
    {value: '335i', label: '335i', link: 'bmw'},
    {value: '335is', label: '335is', link: 'bmw'},
    {value: '335xi', label: '335xi', link: 'bmw'},
    {value: 'ActiveHybrid 3', label: 'ActiveHybrid 3', link: 'bmw'},
    {value: '325', label: '325', link: 'bmw'},
    {value: '524td', label: '524td', link: 'bmw'},
    {value: '525i', label: '525i', link: 'bmw'},
    {value: '525xi', label: '525xi', link: 'bmw'},
    {value: '528e', label: '528e', link: 'bmw'},
    {value: '528i', label: '528i', link: 'bmw'},
    {value: '528iT', label: '528iT', link: 'bmw'},
    {value: '528xi', label: '528xi', link: 'bmw'},
    {value: '530i', label: '530i', link: 'bmw'},
    {value: '530iT', label: '530iT', link: 'bmw'},
    {value: '530xi', label: '530xi', link: 'bmw'},
    {value: '533i', label: '533i', link: 'bmw'},
    {value: '535i', label: '535i', link: 'bmw'},
    {value: '535i Gran Turismo', label: '535i Gran Turismo', link: 'bmw'},
    {value: '535xi', label: '535xi', link: 'bmw'},
    {value: '540i', label: '540i', link: 'bmw'},
    {value: '545i', label: '545i', link: 'bmw'},
    {value: '550i', label: '550i', link: 'bmw'},
    {value: '550i Gran Turismo', label: '550i Gran Turismo', link: 'bmw'},
    {value: 'ActiveHybrid 5', label: 'ActiveHybrid 5', link: 'bmw'},
    {value: '633CSi', label: '633CSi', link: 'bmw'},
    {value: '635CSi', label: '635CSi', link: 'bmw'},
    {value: '640i', label: '640i', link: 'bmw'},
    {value: '640i Gran Coupe', label: '640i Gran Coupe', link: 'bmw'},
    {value: '645Ci', label: '645Ci', link: 'bmw'},
    {value: '650i', label: '650i', link: 'bmw'},
    {value: '650i Gran Coupe', label: '650i Gran Coupe', link: 'bmw'},
    {value: 'L6', label: 'L6', link: 'bmw'},
    {value: '733i', label: '733i', link: 'bmw'},
    {value: '735i', label: '735i', link: 'bmw'},
    {value: '735iL', label: '735iL', link: 'bmw'},
    {value: '740i', label: '740i', link: 'bmw'},
    {value: '740iL', label: '740iL', link: 'bmw'},
    {value: '740Li', label: '740Li', link: 'bmw'},
    {value: '745i', label: '745i', link: 'bmw'},
    {value: '745Li', label: '745Li', link: 'bmw'},
    {value: '750i', label: '750i', link: 'bmw'},
    {value: '750iL', label: '750iL', link: 'bmw'},
    {value: '750Li', label: '750Li', link: 'bmw'},
    {value: '760i', label: '760i', link: 'bmw'},
    {value: '760Li', label: '760Li', link: 'bmw'},
    {value: 'ActiveHybrid 7', label: 'ActiveHybrid 7', link: 'bmw'},
    {value: 'Alpina B7', label: 'Alpina B7', link: 'bmw'},
    {value: '840Ci', label: '840Ci', link: 'bmw'},
    {value: '850Ci', label: '850Ci', link: 'bmw'},
    {value: '850CSi', label: '850CSi', link: 'bmw'},
    {value: '850i', label: '850i', link: 'bmw'},
    {value: 'L7', label: 'L7', link: 'bmw'},
    {value: '1 Series M', label: '1 Series M', link: 'bmw'},
    {value: 'M Coupe', label: 'M Coupe', link: 'bmw'},
    {value: 'M Roadster', label: 'M Roadster', link: 'bmw'},
    {value: 'M3', label: 'M3', link: 'bmw'},
    {value: 'M5', label: 'M5', link: 'bmw'},
    {value: 'M6', label: 'M6', link: 'bmw'},
    {value: 'X5 M', label: 'X5 M', link: 'bmw'},
    {value: 'X6 M', label: 'X6 M', link: 'bmw'},
    {value: 'ActiveHybrid X6', label: 'ActiveHybrid X6', link: 'bmw'},
    {value: 'X1', label: 'X1', link: 'bmw'},
    {value: 'X3', label: 'X3', link: 'bmw'},
    {value: 'X5', label: 'X5', link: 'bmw'},
    {value: 'X6', label: 'X6', link: 'bmw'},
    {value: 'Z3', label: 'Z3', link: 'bmw'},
    {value: 'Z4', label: 'Z4', link: 'bmw'},
    {value: 'Z8', label: 'Z8', link: 'bmw'},
];
