export const marksOfCars = [
    {value: 'acura', label: 'Acura'},
    {value: 'alfa romeo', label: 'Alfa Romeo'},
    {value: 'amc', label: 'AMC'},
    {value: 'aston martin', label: 'Aston Martin'},
    {value: 'audi', label: 'Audi'},
  ];

export const modelsOfCars = [
    {value: '2.2CL', label: '2.2CL', link: 'acura'},
    {value: '2.3CL', label: '2.3CL', link: 'acura'},
    {value: '3.0CL', label: '3.0CL', link: 'acura'},
    {value: '3.2CL', label: '3.2CL', link: 'acura'},
    {value: 'ILX', label: 'ILX', link: 'acura'},
    {value: 'Integra', label: 'Integra', link: 'acura'},
    {value: 'Legend', label: 'Legend', link: 'acura'},
    {value: 'MDX', label: 'MDX', link: 'acura'},
    {value: 'NSX', label: 'NSX', link: 'acura'},
    {value: 'RDX', label: 'RDX', link: 'acura'},
    {value: '3.5 RL', label: '3.5 RL', link: 'acura'},
    {value: 'RL', label: 'RL', link: 'acura'},
    {value: 'RSX', label: 'RSX', link: 'acura'},
    {value: 'SLX', label: 'SLX', link: 'acura'},
    {value: '2.5TL', label: '2.5TL', link: 'acura'},
    {value: '3.2TL', label: '3.2TL', link: 'acura'},
    {value: 'TL', label: 'TL', link: 'acura'},
    {value: 'TSX', label: 'TSX', link: 'acura'},
    {value: 'Vigor', label: 'Vigor', link: 'acura'},
    {value: 'ZDX', label: 'ZDX', link: 'acura'},
    {value: '164', label: '164', link: 'alfa romeo'},
    {value: '8C Competizione', label: '8C Competizione', link: 'alfa romeo'},
    {value: 'GTV-6', label: 'GTV-6', link: 'alfa romeo'},
    {value: 'Milano', label: 'Milano', link: 'alfa romeo'},
    {value: 'Spider', label: 'Spider', link: 'alfa romeo'},
    {value: 'Alliance', label: 'Alliance', link: 'amc'},
    {value: 'Concord', label: 'Concord', link: 'amc'},
    {value: 'Eagle', label: 'Eagle', link: 'amc'},
    {value: 'Encore', label: 'Encore', link: 'amc'},
    {value: 'Spirit', label: 'Spirit', link: 'amc'},
    {value: 'DB7', label: 'DB7', link: 'aston martin'},
    {value: 'DB9', label: 'DB9', link: 'aston martin'},
    {value: 'DBS', label: 'DBS', link: 'aston martin'},
    {value: 'Lagonda', label: 'Lagonda', link: 'aston martin'},
    {value: 'Rapide', label: 'Rapide', link: 'aston martin'},
    {value: 'V12 Vantage', label: 'V12 Vantage', link: 'aston martin'},
    {value: 'V8 Vantage', label: 'V8 Vantage', link: 'aston martin'},
    {value: 'Vanquish', label: 'Vanquish', link: 'aston martin'},
    {value: 'Virage', label: 'Virage', link: 'aston martin'},
    {value: '100', label: '100', link: 'audi'},
    {value: '200', label: '200', link: 'audi'},
    {value: '4000', label: '4000', link: 'audi'},
    {value: '5000', label: '5000', link: 'audi'},
    {value: '80', label: '80', link: 'audi'},
    {value: '90', label: '90', link: 'audi'},
    {value: 'A3', label: 'A3', link: 'audi'},
    {value: 'A4', label: 'A4', link: 'audi'},
    {value: 'A5', label: 'A5', link: 'audi'},
    {value: 'A6', label: 'A6', link: 'audi'},
    {value: 'A7', label: 'A7', link: 'audi'},
    {value: 'A8', label: 'A8', link: 'audi'},
    {value: 'allroad', label: 'allroad', link: 'audi'},
    {value: 'Cabriolet', label: 'Cabriolet', link: 'audi'},
    {value: 'Coupe', label: 'Coupe', link: 'audi'},
    {value: 'Q3', label: 'Q3', link: 'audi'},
    {value: 'Q5', label: 'Q5', link: 'audi'},
    {value: 'Q7', label: 'Q7', link: 'audi'},
    {value: 'Quattro', label: 'Quattro', link: 'audi'},
    {value: 'RS 4', label: 'RS 4', link: 'audi'},
    {value: 'RS 5', label: 'RS 5', link: 'audi'},
    {value: 'RS 6', label: 'RS 6', link: 'audi'},
    {value: 'S4', label: 'S4', link: 'audi'},
    {value: 'S5', label: 'S5', link: 'audi'},
    {value: 'S6', label: 'S6', link: 'audi'},
    {value: 'S7', label: 'S7', link: 'audi'},
    {value: 'S8', label: 'S8', link: 'audi'},
    {value: 'TT', label: 'TT', link: 'audi'},
    {value: 'TT RS', label: 'TT RS', link: 'audi'},
    {value: 'TTS', label: 'TTS', link: 'audi'},
    {value: 'V8 Quattro', label: 'V8 Quattro', link: 'audi'},
];
